// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD72jO8pCovwuS_MKOp3Bk80eYFzUL8msY',
    appId: '1:990622787789:web:97f3dfd0fba99752d96184',
    messagingSenderId: '990622787789',
    projectId: 'scooter-app-406700',
    authDomain: 'scooter-app-406700.firebaseapp.com',
    storageBucket: 'scooter-app-406700.appspot.com',
    measurementId: 'G-VDKNKHQNHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAupndeooo8lvzQy9tVuvfQpqoCD_RtLis',
    appId: '1:990622787789:android:33e6b1f5ffcbfdced96184',
    messagingSenderId: '990622787789',
    projectId: 'scooter-app-406700',
    storageBucket: 'scooter-app-406700.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGYHTiOX4x5xbbj4tnaMrcoJjv2SWJrjQ',
    appId: '1:990622787789:ios:f122492aca051adad96184',
    messagingSenderId: '990622787789',
    projectId: 'scooter-app-406700',
    storageBucket: 'scooter-app-406700.appspot.com',
    iosBundleId: 'com.example.scooterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGYHTiOX4x5xbbj4tnaMrcoJjv2SWJrjQ',
    appId: '1:990622787789:ios:38a000c86e1f66ecd96184',
    messagingSenderId: '990622787789',
    projectId: 'scooter-app-406700',
    storageBucket: 'scooter-app-406700.appspot.com',
    iosBundleId: 'com.example.scooterApp.RunnerTests',
  );
}
